### ISSUE TITLE
메뉴 추가 설정

### ISSUE THREAD

**Issue by l2zeo** [curlychoi/miwit-pack5#1]
배추빌더5의 메뉴추가설정에서 출력권한과 함께 접근권한도 추가되었으면 합니다.

**Comment by curlychoi** [comment]
l2zeo 님 반갑습니다!
메뉴별 접근권한은 이미 개발되어 깃허브에는 올라가있습니다.
아직 이것저것 마무리 작업중이라 마이위트에는 올리지 못했네요!
조만간 공지 올리겠습니다. ^^!

**Comment by l2zeo** [comment]
@curlychoi 이슈를 적고 빌더 커밋을 보니..이미 들어가있더라구요 ^^
고생 하셨습니다~
