### ISSUE TITLE
/plugins/logo-planner 이슈입니다

### ISSUE THREAD

**Issue by songwritersg** [curlychoi/miwit-pack5#2]
/plugins/logo-planner/_head.php
/plugins/logo-planner/_lib_lunar.php
두파일이 <? 로 시작이 됩니다

/lib/mw.widget.lib.php 52번째줄에 숏태그가 사용되었습니다.
/theme/miwit/tail.sub.php 15번째줄에 숏태그가 사용되었습니다.

제가 php 설정을 short_tag 허용안함으로 해놨더니
이부분때문에 오류가 발생하더군요 ~
참조하셨으면 하는바람에 작성해봅니다

**Comment by curlychoi** [comment]
정리해주셔서 감사합니다.
